config/routes.rb
Rails.application.routes.draw do
  resources :descontos
  resources :eventos
  resources :estabelecimentos
  resources :geolocalizacaos
  resources :users

end

app/models/geolocalizacao.rb
class Geolocalizacao < ActiveRecord::Base
  belongs_to :users
end

app/controllers/geolocalizacaos_controller.rb
class GeolocalizacaosController < ApplicationController
  before_action :set_geolocalizacao, only: [:show, :edit, :update, :destroy]

  # GET /geolocalizacaos
  # GET /geolocalizacaos.json
  def index
    @geolocalizacaos = Geolocalizacao.all
  end

  # GET /geolocalizacaos/1
  # GET /geolocalizacaos/1.json
  def show
  end

  # GET /geolocalizacaos/new
  def new
    @geolocalizacao = Geolocalizacao.new
  end

  # GET /geolocalizacaos/1/edit
  def edit
  end

  # POST /geolocalizacaos
  # POST /geolocalizacaos.json
  def create
    @geolocalizacao = Geolocalizacao.new(geolocalizacao_params)

    respond_to do |format|
      if @geolocalizacao.save
        format.html { redirect_to @geolocalizacao, notice: 'Geolocalizacao was successfully created.' }
        format.json { render :show, status: :created, location: @geolocalizacao }
      else
        format.html { render :new }
        format.json { render json: @geolocalizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geolocalizacaos/1
  # PATCH/PUT /geolocalizacaos/1.json
  def update
    respond_to do |format|
      if @geolocalizacao.update(geolocalizacao_params)
        format.html { redirect_to @geolocalizacao, notice: 'Geolocalizacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @geolocalizacao }
      else
        format.html { render :edit }
        format.json { render json: @geolocalizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geolocalizacaos/1
  # DELETE /geolocalizacaos/1.json
  def destroy
    @geolocalizacao.destroy
    respond_to do |format|
      format.html { redirect_to geolocalizacaos_url, notice: 'Geolocalizacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geolocalizacao
      @geolocalizacao = Geolocalizacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geolocalizacao_params
      params.require(:geolocalizacao).permit(:latitude, :longitude, :users_id)
    end
end

app/helpers/geolocalizacaos_helper.rb
module GeolocalizacaosHelper
end

app/views/geolocalizacaos/_form.html.erb
<%= form_for(@geolocalizacao) do |f| %>
  <% if @geolocalizacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geolocalizacao.errors.count, "error") %> prohibited this geolocalizacao from being saved:</h2>

      <ul>
      <% @geolocalizacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :users_id %><br>
    <%= f.text_field :users_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geolocalizacaos/_form.html.haml
= simple_form_for(@geolocalizacao) do |f|
  = f.error_notification

  .form-inputs
    = f.input :latitude
    = f.input :longitude
    = f.association :user

  .form-actions
    = f.button :submit

app/views/geolocalizacaos/edit.html.erb
<h1>Editing Geolocalizacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @geolocalizacao %> |
<%= link_to 'Back', geolocalizacaos_path %>

app/views/geolocalizacaos/edit.html.haml
%h1 Editing geolocalizacao

= render 'form'

= link_to 'Show', @geolocalizacao
\|
= link_to 'Back', geolocalizacaos_path

app/views/geolocalizacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Geolocalizacaos</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geolocalizacaos.each do |geolocalizacao| %>
      <tr>
        <td><%= geolocalizacao.latitude %></td>
        <td><%= geolocalizacao.longitude %></td>
        <td><%= geolocalizacao.users %></td>
        <td><%= link_to 'Show', geolocalizacao %></td>
        <td><%= link_to 'Edit', edit_geolocalizacao_path(geolocalizacao) %></td>
        <td><%= link_to 'Destroy', geolocalizacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geolocalizacao', new_geolocalizacao_path %>

app/views/geolocalizacaos/index.html.haml
%h1 Listing geolocalizacaos

%table
  %thead
    %tr
      %th Latitude
      %th Longitude
      %th User
      %th
      %th
      %th

  %tbody
    - @geolocalizacaos.each do |geolocalizacao|
      %tr
        %td= geolocalizacao.latitude
        %td= geolocalizacao.longitude
        %td= geolocalizacao.user
        %td= link_to 'Show', geolocalizacao
        %td= link_to 'Edit', edit_geolocalizacao_path(geolocalizacao)
        %td= link_to 'Destroy', geolocalizacao, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Geolocalizacao', new_geolocalizacao_path

app/views/geolocalizacaos/new.html.erb
<h1>New Geolocalizacao</h1>

<%= render 'form' %>

<%= link_to 'Back', geolocalizacaos_path %>

app/views/geolocalizacaos/new.html.haml
%h1 New geolocalizacao

= render 'form'

= link_to 'Back', geolocalizacaos_path

app/views/geolocalizacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @geolocalizacao.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @geolocalizacao.longitude %>
</p>

<p>
  <strong>Users:</strong>
  <%= @geolocalizacao.users %>
</p>

<%= link_to 'Edit', edit_geolocalizacao_path(@geolocalizacao) %> |
<%= link_to 'Back', geolocalizacaos_path %>

app/views/geolocalizacaos/show.html.haml
%p#notice= notice

%p
  %b Latitude:
  = @geolocalizacao.latitude
%p
  %b Longitude:
  = @geolocalizacao.longitude
%p
  %b User:
  = @geolocalizacao.user

= link_to 'Edit', edit_geolocalizacao_path(@geolocalizacao)
\|
= link_to 'Back', geolocalizacaos_path