config/routes.rb
Rails.application.routes.draw do
  resources :descontos
  resources :eventos
  resources :estabelecimentos
  resources :geolocalizacaos
  resources :users

end

app/models/desconto.rb
class Desconto < ActiveRecord::Base
  belongs_to :user
end

app/controllers/descontos_controller.rb
class DescontosController < ApplicationController
  before_action :set_desconto, only: [:show, :edit, :update, :destroy]

  # GET /descontos
  # GET /descontos.json
  def index
    @descontos = Desconto.all
  end

  # GET /descontos/1
  # GET /descontos/1.json
  def show
  end

  # GET /descontos/new
  def new
    @desconto = Desconto.new
  end

  # GET /descontos/1/edit
  def edit
  end

  # POST /descontos
  # POST /descontos.json
  def create
    @desconto = Desconto.new(desconto_params)

    respond_to do |format|
      if @desconto.save
        format.html { redirect_to @desconto, notice: 'Desconto was successfully created.' }
        format.json { render :show, status: :created, location: @desconto }
      else
        format.html { render :new }
        format.json { render json: @desconto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /descontos/1
  # PATCH/PUT /descontos/1.json
  def update
    respond_to do |format|
      if @desconto.update(desconto_params)
        format.html { redirect_to @desconto, notice: 'Desconto was successfully updated.' }
        format.json { render :show, status: :ok, location: @desconto }
      else
        format.html { render :edit }
        format.json { render json: @desconto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descontos/1
  # DELETE /descontos/1.json
  def destroy
    @desconto.destroy
    respond_to do |format|
      format.html { redirect_to descontos_url, notice: 'Desconto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desconto
      @desconto = Desconto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desconto_params
      params.require(:desconto).permit(:porcentagem, :user_id)
    end
end

app/helpers/descontos_helper.rb
module DescontosHelper
end

app/views/descontos/_form.html.erb
<%= form_for(@desconto) do |f| %>
  <% if @desconto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@desconto.errors.count, "error") %> prohibited this desconto from being saved:</h2>

      <ul>
      <% @desconto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :porcentagem %><br>
    <%= f.text_field :porcentagem %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/descontos/_form.html.haml
= simple_form_for(@desconto) do |f|
  = f.error_notification

  .form-inputs
    = f.input :porcentagem
    = f.association :user

  .form-actions
    = f.button :submit

app/views/descontos/edit.html.erb
<h1>Editing Desconto</h1>

<%= render 'form' %>

<%= link_to 'Show', @desconto %> |
<%= link_to 'Back', descontos_path %>

app/views/descontos/edit.html.haml
%h1 Editing desconto

= render 'form'

= link_to 'Show', @desconto
\|
= link_to 'Back', descontos_path

app/views/descontos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Descontos</h1>

<table>
  <thead>
    <tr>
      <th>Porcentagem</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @descontos.each do |desconto| %>
      <tr>
        <td><%= desconto.porcentagem %></td>
        <td><%= desconto.user %></td>
        <td><%= link_to 'Show', desconto %></td>
        <td><%= link_to 'Edit', edit_desconto_path(desconto) %></td>
        <td><%= link_to 'Destroy', desconto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Desconto', new_desconto_path %>

app/views/descontos/index.html.haml
%h1 Listing descontos

%table
  %thead
    %tr
      %th Porcentagem
      %th User
      %th
      %th
      %th

  %tbody
    - @descontos.each do |desconto|
      %tr
        %td= desconto.porcentagem
        %td= desconto.user
        %td= link_to 'Show', desconto
        %td= link_to 'Edit', edit_desconto_path(desconto)
        %td= link_to 'Destroy', desconto, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Desconto', new_desconto_path

app/views/descontos/new.html.erb
<h1>New Desconto</h1>

<%= render 'form' %>

<%= link_to 'Back', descontos_path %>

app/views/descontos/new.html.haml
%h1 New desconto

= render 'form'

= link_to 'Back', descontos_path

app/views/descontos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Porcentagem:</strong>
  <%= @desconto.porcentagem %>
</p>

<p>
  <strong>User:</strong>
  <%= @desconto.user %>
</p>

<%= link_to 'Edit', edit_desconto_path(@desconto) %> |
<%= link_to 'Back', descontos_path %>

app/views/descontos/show.html.haml
%p#notice= notice

%p
  %b Porcentagem:
  = @desconto.porcentagem
%p
  %b User:
  = @desconto.user

= link_to 'Edit', edit_desconto_path(@desconto)
\|
= link_to 'Back', descontos_path