config/routes.rb
Rails.application.routes.draw do
  resources :descontos
  resources :eventos
  resources :estabelecimentos
  resources :geolocalizacaos
  resources :users

end

app/models/estabelecimento.rb
class Estabelecimento < ActiveRecord::Base
end

app/controllers/estabelecimentos_controller.rb
class EstabelecimentosController < ApplicationController
  before_action :set_estabelecimento, only: [:show, :edit, :update, :destroy]

  # GET /estabelecimentos
  # GET /estabelecimentos.json
  def index
    @estabelecimentos = Estabelecimento.all
  end

  # GET /estabelecimentos/1
  # GET /estabelecimentos/1.json
  def show
  end

  # GET /estabelecimentos/new
  def new
    @estabelecimento = Estabelecimento.new
  end

  # GET /estabelecimentos/1/edit
  def edit
  end

  # POST /estabelecimentos
  # POST /estabelecimentos.json
  def create
    @estabelecimento = Estabelecimento.new(estabelecimento_params)

    respond_to do |format|
      if @estabelecimento.save
        format.html { redirect_to @estabelecimento, notice: 'Estabelecimento was successfully created.' }
        format.json { render :show, status: :created, location: @estabelecimento }
      else
        format.html { render :new }
        format.json { render json: @estabelecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estabelecimentos/1
  # PATCH/PUT /estabelecimentos/1.json
  def update
    respond_to do |format|
      if @estabelecimento.update(estabelecimento_params)
        format.html { redirect_to @estabelecimento, notice: 'Estabelecimento was successfully updated.' }
        format.json { render :show, status: :ok, location: @estabelecimento }
      else
        format.html { render :edit }
        format.json { render json: @estabelecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estabelecimentos/1
  # DELETE /estabelecimentos/1.json
  def destroy
    @estabelecimento.destroy
    respond_to do |format|
      format.html { redirect_to estabelecimentos_url, notice: 'Estabelecimento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estabelecimento
      @estabelecimento = Estabelecimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estabelecimento_params
      params.require(:estabelecimento).permit(:nome, :cnpj)
    end
end

app/helpers/estabelecimentos_helper.rb
module EstabelecimentosHelper
end

app/views/estabelecimentos/_form.html.erb
<%= form_for(@estabelecimento) do |f| %>
  <% if @estabelecimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estabelecimento.errors.count, "error") %> prohibited this estabelecimento from being saved:</h2>

      <ul>
      <% @estabelecimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estabelecimentos/edit.html.erb
<h1>Editing Estabelecimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @estabelecimento %> |
<%= link_to 'Back', estabelecimentos_path %>

app/views/estabelecimentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estabelecimentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estabelecimentos.each do |estabelecimento| %>
      <tr>
        <td><%= estabelecimento.nome %></td>
        <td><%= estabelecimento.cnpj %></td>
        <td><%= link_to 'Show', estabelecimento %></td>
        <td><%= link_to 'Edit', edit_estabelecimento_path(estabelecimento) %></td>
        <td><%= link_to 'Destroy', estabelecimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estabelecimento', new_estabelecimento_path %>

app/views/estabelecimentos/new.html.erb
<h1>New Estabelecimento</h1>

<%= render 'form' %>

<%= link_to 'Back', estabelecimentos_path %>

app/views/estabelecimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estabelecimento.nome %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @estabelecimento.cnpj %>
</p>

<%= link_to 'Edit', edit_estabelecimento_path(@estabelecimento) %> |
<%= link_to 'Back', estabelecimentos_path %>